#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: __SMARTHUB_HOSTNAME__
    username: __SMARTHUB_BOOTSTRAP_USER__
    password: "$6$placeholder$placeholder"
  ssh:
    allow-pw: true
    install-server: true
  packages:
    - git
    - curl
    - python3
    - openssh-server
